"""
Synaphe Python Transpiler — Converts Synaphe AST to idiomatic Python code.
Generates Python that uses PyTorch for tensors, Qiskit/PennyLane for quantum,
and standard Python for everything else.
"""

from typing import List, Optional
from .ast_nodes import *


class TranspilerError(Exception):
    pass


class PythonTranspiler:
    def __init__(self):
        self.indent_level = 0
        self.imports = set()
        self.output_lines = []
        self.has_quantum = False
        self.has_tensors = False
        self.has_model = False
        self.has_pipeline = False
        self.has_grad = False
    
    def indent(self) -> str:
        return "    " * self.indent_level
    
    def emit(self, line: str):
        self.output_lines.append(f"{self.indent()}{line}")
    
    def emit_raw(self, line: str):
        self.output_lines.append(line)
    
    # ── Main Entry ────────────────────────────────────────────────────
    
    def transpile(self, program: Program) -> str:
        # First pass: scan for features used
        self._scan_features(program)
        
        # Generate imports
        header = self._generate_header()
        
        # Generate body
        for stmt in program.statements:
            self.transpile_statement(stmt)
        
        return header + "\n" + "\n".join(self.output_lines)
    
    def _scan_features(self, program: Program):
        """Scan AST to determine what imports/runtime features are needed."""
        for stmt in program.statements:
            self._scan_node(stmt)
    
    def _scan_node(self, node):
        if isinstance(node, (TensorType, MatMul)):
            self.has_tensors = True
        if isinstance(node, ModelDef):
            self.has_model = True
            self.has_tensors = True
        if isinstance(node, Pipeline):
            self.has_pipeline = True
        if isinstance(node, GradCall):
            self.has_grad = True
            self.has_tensors = True
        if isinstance(node, Identifier) and node.name in ('qubit', 'qregister', 'measure', 'hadamard', 'cx', 'rx', 'ry', 'rz'):
            self.has_quantum = True
        
        # Recurse into children
        for attr_name in vars(node):
            attr = getattr(node, attr_name)
            if isinstance(attr, ASTNode):
                self._scan_node(attr)
            elif isinstance(attr, list):
                for item in attr:
                    if isinstance(item, ASTNode):
                        self._scan_node(item)
            elif isinstance(attr, dict):
                for v in attr.values():
                    if isinstance(v, ASTNode):
                        self._scan_node(v)
                    elif isinstance(v, list):
                        for item in v:
                            if isinstance(item, ASTNode):
                                self._scan_node(item)
    
    def _generate_header(self) -> str:
        lines = [
            "#!/usr/bin/env python3",
            '"""Generated by Synaphe transpiler — https://github.com/synaphe-project"""',
            ""
        ]
        
        if self.has_tensors:
            lines.append("import torch")
            lines.append("import torch.nn as nn")
            lines.append("import torch.nn.functional as F")
        
        if self.has_model:
            lines.append("from torch.optim import Adam, SGD, AdamW")
        
        if self.has_quantum:
            lines.append("import pennylane as qml")
            lines.append("import numpy as np")
        
        if self.has_pipeline:
            lines.append("from functools import reduce")
        
        if self.has_grad:
            lines.append("import torch.autograd as autograd")
        
        lines.append("import math")
        lines.append("")
        
        # Pipeline helper
        if self.has_pipeline:
            lines.extend([
                "def _synaphe_pipeline(initial, *fns):",
                "    \"\"\"Synaphe pipeline operator |> runtime.\"\"\"",
                "    result = initial",
                "    for fn in fns:",
                "        if callable(fn):",
                "            result = fn(result)",
                "        else:",
                "            result = fn",
                "    return result",
                ""
            ])
        
        return "\n".join(lines)
    
    # ── Statements ────────────────────────────────────────────────────
    
    def transpile_statement(self, stmt: Statement):
        if isinstance(stmt, LetStatement):
            self._transpile_let(stmt)
        elif isinstance(stmt, FunctionDef):
            self._transpile_function(stmt)
        elif isinstance(stmt, ReturnStatement):
            self._transpile_return(stmt)
        elif isinstance(stmt, IfStatement):
            self._transpile_if(stmt)
        elif isinstance(stmt, ForLoop):
            self._transpile_for(stmt)
        elif isinstance(stmt, WhileLoop):
            self._transpile_while(stmt)
        elif isinstance(stmt, ImportStatement):
            self._transpile_import(stmt)
        elif isinstance(stmt, ModelDef):
            self._transpile_model(stmt)
        elif isinstance(stmt, SchemaDef):
            self._transpile_schema(stmt)
        elif isinstance(stmt, TypeAlias):
            self._transpile_type_alias(stmt)
        elif isinstance(stmt, ExprStatement):
            expr_code = self.transpile_expr(stmt.expr)
            self.emit(expr_code)
        else:
            self.emit(f"# TODO: {type(stmt).__name__}")
    
    def _transpile_let(self, stmt: LetStatement):
        value_code = self.transpile_expr(stmt.value)
        
        # Add type annotation comment if present
        if stmt.type_annotation:
            type_str = self._type_to_str(stmt.type_annotation)
            self.emit(f"{stmt.name}: {type_str} = {value_code}")
        else:
            self.emit(f"{stmt.name} = {value_code}")
    
    def _transpile_function(self, stmt: FunctionDef):
        # Decorators
        for dec in stmt.decorators:
            if 'target' in dec:
                self.emit(f"# {dec}")
                self.emit("@torch.no_grad()  # target hint for compiler")
            elif 'differentiable' in dec:
                self.emit("# @differentiable — gradients tracked automatically")
            else:
                self.emit(f"# {dec}")
        
        # Function signature
        params = []
        for p in stmt.params:
            param_str = p.name
            if p.type_annotation:
                param_str += f": {self._type_to_python(p.type_annotation)}"
            if p.default:
                param_str += f" = {self.transpile_expr(p.default)}"
            params.append(param_str)
        
        ret_type = ""
        if stmt.return_type:
            ret_type = f" -> {self._type_to_python(stmt.return_type)}"
        
        self.emit(f"def {stmt.name}({', '.join(params)}){ret_type}:")
        
        self.indent_level += 1
        if not stmt.body:
            self.emit("pass")
        else:
            for s in stmt.body:
                self.transpile_statement(s)
        self.indent_level -= 1
        self.emit("")
    
    def _transpile_return(self, stmt: ReturnStatement):
        if stmt.value:
            self.emit(f"return {self.transpile_expr(stmt.value)}")
        else:
            self.emit("return")
    
    def _transpile_if(self, stmt: IfStatement):
        self.emit(f"if {self.transpile_expr(stmt.condition)}:")
        self.indent_level += 1
        for s in stmt.then_body:
            self.transpile_statement(s)
        if not stmt.then_body:
            self.emit("pass")
        self.indent_level -= 1
        
        if stmt.else_body:
            if len(stmt.else_body) == 1 and isinstance(stmt.else_body[0], IfStatement):
                self.emit(f"elif {self.transpile_expr(stmt.else_body[0].condition)}:")
                self.indent_level += 1
                for s in stmt.else_body[0].then_body:
                    self.transpile_statement(s)
                self.indent_level -= 1
                if stmt.else_body[0].else_body:
                    # Recurse for elif chains
                    self._transpile_else_chain(stmt.else_body[0].else_body)
            else:
                self.emit("else:")
                self.indent_level += 1
                for s in stmt.else_body:
                    self.transpile_statement(s)
                self.indent_level -= 1
    
    def _transpile_else_chain(self, else_body):
        if len(else_body) == 1 and isinstance(else_body[0], IfStatement):
            self.emit(f"elif {self.transpile_expr(else_body[0].condition)}:")
            self.indent_level += 1
            for s in else_body[0].then_body:
                self.transpile_statement(s)
            self.indent_level -= 1
            if else_body[0].else_body:
                self._transpile_else_chain(else_body[0].else_body)
        else:
            self.emit("else:")
            self.indent_level += 1
            for s in else_body:
                self.transpile_statement(s)
            self.indent_level -= 1
    
    def _transpile_for(self, stmt: ForLoop):
        self.emit(f"for {stmt.var} in {self.transpile_expr(stmt.iterable)}:")
        self.indent_level += 1
        for s in stmt.body:
            self.transpile_statement(s)
        if not stmt.body:
            self.emit("pass")
        self.indent_level -= 1
    
    def _transpile_while(self, stmt: WhileLoop):
        self.emit(f"while {self.transpile_expr(stmt.condition)}:")
        self.indent_level += 1
        for s in stmt.body:
            self.transpile_statement(s)
        if not stmt.body:
            self.emit("pass")
        self.indent_level -= 1
    
    def _transpile_import(self, stmt: ImportStatement):
        if stmt.names:
            names = ", ".join(stmt.names)
            self.emit(f"from {stmt.module} import {names}")
        elif stmt.alias:
            self.emit(f"import {stmt.module} as {stmt.alias}")
        else:
            self.emit(f"import {stmt.module}")
    
    def _transpile_model(self, stmt: ModelDef):
        self.emit(f"class {stmt.name}(nn.Module):")
        self.indent_level += 1
        
        # __init__
        self.emit("def __init__(self):")
        self.indent_level += 1
        self.emit(f"super({stmt.name}, self).__init__()")
        
        if 'layers' in stmt.fields and isinstance(stmt.fields['layers'], list):
            activation_names = {'ReLU', 'GELU', 'Tanh', 'Sigmoid', 'LeakyReLU', 'ELU', 'SiLU', 'Softmax'}
            for i, layer_expr in enumerate(stmt.fields['layers']):
                layer_code = self.transpile_expr(layer_expr)
                # Bare activation names -> nn.Name()
                if isinstance(layer_expr, Identifier) and layer_expr.name in activation_names:
                    layer_code = f"nn.{layer_expr.name}()"
                self.emit(f"self.layer_{i} = {layer_code}")
        
        if 'optimizer' in stmt.fields:
            opt_code = self.transpile_expr(stmt.fields['optimizer'])
            self.emit(f"# Optimizer: {opt_code}")
        
        if 'loss' in stmt.fields:
            loss_code = self.transpile_expr(stmt.fields['loss'])
            self.emit(f"self.loss_fn = nn.{loss_code}()")
        
        self.indent_level -= 1
        self.emit("")
        
        # forward
        self.emit("def forward(self, x):")
        self.indent_level += 1
        if 'layers' in stmt.fields and isinstance(stmt.fields['layers'], list):
            for i, _ in enumerate(stmt.fields['layers']):
                self.emit(f"x = self.layer_{i}(x)")
        self.emit("return x")
        self.indent_level -= 1
        
        self.indent_level -= 1
        self.emit("")
    
    def _transpile_schema(self, stmt: SchemaDef):
        self.emit(f"class {stmt.name}:")
        self.indent_level += 1
        self.emit('"""Data schema with runtime validation."""')
        self.emit("")
        
        # Validation method
        self.emit("@staticmethod")
        self.emit("def validate(data):")
        self.indent_level += 1
        
        for field in stmt.fields:
            field_type = self._type_to_str(field.type_annotation)
            self.emit(f"# Validate {field.name}: {field_type}")
            if field.constraint:
                constraint_code = self.transpile_expr(field.constraint)
                self.emit(f"assert {constraint_code}, f\"Validation failed for {field.name}\"")
        
        self.emit("return True")
        self.indent_level -= 1
        self.indent_level -= 1
        self.emit("")
    
    def _transpile_type_alias(self, stmt: TypeAlias):
        type_str = self._type_to_str(stmt.definition)
        self.emit(f"# type {stmt.name} = {type_str}")
        self.emit(f"{stmt.name} = '{type_str}'  # Type alias")
    
    # ── Expressions ───────────────────────────────────────────────────
    
    def transpile_expr(self, expr: Expression) -> str:
        if isinstance(expr, IntLiteral):
            return str(expr.value)
        
        if isinstance(expr, FloatLiteral):
            return str(expr.value)
        
        if isinstance(expr, StringLiteral):
            return repr(expr.value)
        
        if isinstance(expr, BoolLiteral):
            return "True" if expr.value else "False"
        
        if isinstance(expr, Identifier):
            return self._map_identifier(expr.name)
        
        if isinstance(expr, BinaryOp):
            left = self.transpile_expr(expr.left)
            right = self.transpile_expr(expr.right)
            op = self._map_operator(expr.op)
            return f"({left} {op} {right})"
        
        if isinstance(expr, UnaryOp):
            operand = self.transpile_expr(expr.operand)
            op = 'not ' if expr.op == '!' else expr.op
            return f"({op}{operand})"
        
        if isinstance(expr, MatMul):
            left = self.transpile_expr(expr.left)
            right = self.transpile_expr(expr.right)
            return f"({left} @ {right})"
        
        if isinstance(expr, Pipeline):
            return self._transpile_pipeline(expr)
        
        if isinstance(expr, FunctionCall):
            return self._transpile_call(expr)
        
        if isinstance(expr, MethodCall):
            obj = self.transpile_expr(expr.object)
            args = ", ".join(self.transpile_expr(a) for a in expr.args)
            return f"{obj}.{expr.method}({args})"
        
        if isinstance(expr, MemberAccess):
            obj = self.transpile_expr(expr.object)
            return f"{obj}.{expr.member}"
        
        if isinstance(expr, IndexAccess):
            obj = self.transpile_expr(expr.object)
            idx = self.transpile_expr(expr.index)
            return f"{obj}[{idx}]"
        
        if isinstance(expr, ListLiteral):
            elems = ", ".join(self.transpile_expr(e) for e in expr.elements)
            return f"[{elems}]"
        
        if isinstance(expr, DictLiteral):
            pairs = ", ".join(
                f"{self.transpile_expr(k)}: {self.transpile_expr(v)}"
                for k, v in expr.pairs
            )
            return "{" + pairs + "}"
        
        if isinstance(expr, MatchExpr):
            return self._transpile_match(expr)
        
        if isinstance(expr, IfExpr):
            then = self.transpile_expr(expr.then_branch)
            cond = self.transpile_expr(expr.condition)
            els = self.transpile_expr(expr.else_branch) if expr.else_branch else "None"
            return f"({then} if {cond} else {els})"
        
        return f"# TODO: {type(expr).__name__}"
    
    def _transpile_pipeline(self, pipe: Pipeline) -> str:
        """Convert |> pipeline to function composition."""
        if len(pipe.stages) == 1:
            return self.transpile_expr(pipe.stages[0])
        
        first = self.transpile_expr(pipe.stages[0])
        rest = ", ".join(self.transpile_expr(s) for s in pipe.stages[1:])
        return f"_synaphe_pipeline({first}, {rest})"
    
    def _transpile_call(self, call: FunctionCall) -> str:
        callee = self.transpile_expr(call.callee)
        
        args = [self.transpile_expr(a) for a in call.args]
        kwargs = [f"{k}={self.transpile_expr(v)}" for k, v in call.kwargs.items()]
        all_args = ", ".join(args + kwargs)
        
        # Map Flux built-in functions to Python equivalents
        builtin_map = {
            'print': 'print',
            'len': 'len',
            'range': 'range',
            'abs': 'abs',
            'max': 'max',
            'min': 'min',
            'sum': 'sum',
            'sorted': 'sorted',
            # Tensor operations
            'zeros': 'torch.zeros',
            'ones': 'torch.ones',
            'randn': 'torch.randn',
            'tensor': 'torch.tensor',
            'reshape': 'torch.reshape',
            'concat': 'torch.cat',
            'stack': 'torch.stack',
            'softmax': 'F.softmax',
            'relu': 'F.relu',
            'sigmoid': 'torch.sigmoid',
            'tanh': 'torch.tanh',
            # Neural network layers
            'Linear': 'nn.Linear',
            'Conv2d': 'nn.Conv2d',
            'BatchNorm2d': 'nn.BatchNorm2d',
            'Dropout': 'nn.Dropout',
            'ReLU': 'nn.ReLU()',
            'GELU': 'nn.GELU()',
            'LayerNorm': 'nn.LayerNorm',
            # Loss functions
            'CrossEntropy': 'CrossEntropyLoss',
            'MSELoss': 'MSELoss',
            # Optimizers
            'Adam': 'Adam',
            'SGD': 'SGD',
            'AdamW': 'AdamW',
            # Quantum operations
            'qubit': 'qml.QubitDevice',
            'hadamard': 'qml.Hadamard',
            'cx': 'qml.CNOT',
            'rx': 'qml.RX',
            'ry': 'qml.RY',
            'rz': 'qml.RZ',
            'measure': 'qml.measure',
        }
        
        mapped = builtin_map.get(callee, callee)
        
        # Special handling for activation functions that are already instantiated
        if mapped.endswith('()') and not all_args:
            return mapped
        
        return f"{mapped}({all_args})"
    
    def _transpile_match(self, expr: MatchExpr) -> str:
        # Python 3.10+ match/case
        subject = self.transpile_expr(expr.subject)
        lines = [f"match {subject}:"]
        for arm in expr.arms:
            pattern = self._pattern_to_str(arm.pattern)
            body = self.transpile_expr(arm.body)
            lines.append(f"    case {pattern}: {body}")
        return "\n".join(lines)
    
    def _pattern_to_str(self, pattern: Pattern) -> str:
        if isinstance(pattern, WildcardPattern):
            return "_"
        if isinstance(pattern, IdentifierPattern):
            return pattern.name
        if isinstance(pattern, LiteralPattern):
            return repr(pattern.value)
        if isinstance(pattern, ConstructorPattern):
            args = ", ".join(self._pattern_to_str(a) for a in pattern.args)
            return f"{pattern.name}({args})"
        return "_"
    
    def _map_identifier(self, name: str) -> str:
        id_map = {
            'true': 'True',
            'false': 'False',
            'null': 'None',
            'PI': 'math.pi',
            'E': 'math.e',
            'INF': 'float("inf")',
        }
        return id_map.get(name, name)
    
    def _map_operator(self, op: str) -> str:
        op_map = {
            '&&': 'and',
            '||': 'or',
            '!': 'not',
        }
        return op_map.get(op, op)
    
    def _type_to_str(self, type_ann: TypeAnnotation) -> str:
        if isinstance(type_ann, SimpleType):
            return type_ann.name
        if isinstance(type_ann, TensorType):
            shape_str = ", ".join(str(d) for d in type_ann.shape)
            return f"Tensor<{type_ann.dtype}, [{shape_str}]>"
        if isinstance(type_ann, GenericType):
            params = ", ".join(self._type_to_str(p) for p in type_ann.params)
            return f"{type_ann.name}<{params}>"
        if isinstance(type_ann, UnionType):
            variants = " | ".join(self._type_to_str(v) for v in type_ann.variants)
            return variants
        return "Any"
    
    def _type_to_python(self, type_ann: TypeAnnotation) -> str:
        if isinstance(type_ann, SimpleType):
            type_map = {
                'Int': 'int', 'Float': 'float', 'Float32': 'float',
                'Float64': 'float', 'String': 'str', 'Bool': 'bool',
            }
            return type_map.get(type_ann.name, type_ann.name)
        if isinstance(type_ann, TensorType):
            return "torch.Tensor"
        return "Any"


def transpile_to_python(program: Program) -> str:
    """Convenience: AST -> Python source code"""
    transpiler = PythonTranspiler()
    return transpiler.transpile(program)
